/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as AuthVerifyCodeRouteImport } from './routes/auth/verify-code'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardMonitoringRouteImport } from './routes/_dashboard/monitoring'
import { Route as DashboardMobilityIndexRouteImport } from './routes/_dashboard/mobility/index'
import { Route as DashboardSettingsUsersRouteImport } from './routes/_dashboard/settings/users'
import { Route as DashboardSettingsCompaniesRouteImport } from './routes/_dashboard/settings/companies'
import { Route as DashboardMobilityVariablesRouteImport } from './routes/_dashboard/mobility/variables'
import { Route as DashboardMobilitySecurityRouteImport } from './routes/_dashboard/mobility/security'
import { Route as DashboardMobilityForecastRouteImport } from './routes/_dashboard/mobility/forecast'
import { Route as DashboardSettingsRolesIndexRouteImport } from './routes/_dashboard/settings/roles/index'
import { Route as DashboardSettingsRolesRoleIdIndexRouteImport } from './routes/_dashboard/settings/roles/$roleId/index'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthVerifyCodeRoute = AuthVerifyCodeRouteImport.update({
  id: '/verify-code',
  path: '/verify-code',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitoringRoute = DashboardMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMobilityIndexRoute = DashboardMobilityIndexRouteImport.update({
  id: '/mobility/',
  path: '/mobility/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsUsersRoute = DashboardSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsCompaniesRoute =
  DashboardSettingsCompaniesRouteImport.update({
    id: '/settings/companies',
    path: '/settings/companies',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMobilityVariablesRoute =
  DashboardMobilityVariablesRouteImport.update({
    id: '/mobility/variables',
    path: '/mobility/variables',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMobilitySecurityRoute =
  DashboardMobilitySecurityRouteImport.update({
    id: '/mobility/security',
    path: '/mobility/security',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMobilityForecastRoute =
  DashboardMobilityForecastRouteImport.update({
    id: '/mobility/forecast',
    path: '/mobility/forecast',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsRolesIndexRoute =
  DashboardSettingsRolesIndexRouteImport.update({
    id: '/settings/roles/',
    path: '/settings/roles/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsRolesRoleIdIndexRoute =
  DashboardSettingsRolesRoleIdIndexRouteImport.update({
    id: '/settings/roles/$roleId/',
    path: '/settings/roles/$roleId/',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/monitoring': typeof DashboardMonitoringRoute
  '/profile': typeof DashboardProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/verify-code': typeof AuthVerifyCodeRoute
  '/': typeof DashboardIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/mobility/forecast': typeof DashboardMobilityForecastRoute
  '/mobility/security': typeof DashboardMobilitySecurityRoute
  '/mobility/variables': typeof DashboardMobilityVariablesRoute
  '/settings/companies': typeof DashboardSettingsCompaniesRoute
  '/settings/users': typeof DashboardSettingsUsersRoute
  '/mobility': typeof DashboardMobilityIndexRoute
  '/settings/roles': typeof DashboardSettingsRolesIndexRoute
  '/settings/roles/$roleId': typeof DashboardSettingsRolesRoleIdIndexRoute
}
export interface FileRoutesByTo {
  '/monitoring': typeof DashboardMonitoringRoute
  '/profile': typeof DashboardProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/verify-code': typeof AuthVerifyCodeRoute
  '/': typeof DashboardIndexRoute
  '/auth': typeof AuthIndexRoute
  '/mobility/forecast': typeof DashboardMobilityForecastRoute
  '/mobility/security': typeof DashboardMobilitySecurityRoute
  '/mobility/variables': typeof DashboardMobilityVariablesRoute
  '/settings/companies': typeof DashboardSettingsCompaniesRoute
  '/settings/users': typeof DashboardSettingsUsersRoute
  '/mobility': typeof DashboardMobilityIndexRoute
  '/settings/roles': typeof DashboardSettingsRolesIndexRoute
  '/settings/roles/$roleId': typeof DashboardSettingsRolesRoleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_dashboard/monitoring': typeof DashboardMonitoringRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/verify-code': typeof AuthVerifyCodeRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_dashboard/mobility/forecast': typeof DashboardMobilityForecastRoute
  '/_dashboard/mobility/security': typeof DashboardMobilitySecurityRoute
  '/_dashboard/mobility/variables': typeof DashboardMobilityVariablesRoute
  '/_dashboard/settings/companies': typeof DashboardSettingsCompaniesRoute
  '/_dashboard/settings/users': typeof DashboardSettingsUsersRoute
  '/_dashboard/mobility/': typeof DashboardMobilityIndexRoute
  '/_dashboard/settings/roles/': typeof DashboardSettingsRolesIndexRoute
  '/_dashboard/settings/roles/$roleId/': typeof DashboardSettingsRolesRoleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/monitoring'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/update-password'
    | '/auth/verify-code'
    | '/'
    | '/auth/'
    | '/mobility/forecast'
    | '/mobility/security'
    | '/mobility/variables'
    | '/settings/companies'
    | '/settings/users'
    | '/mobility'
    | '/settings/roles'
    | '/settings/roles/$roleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/monitoring'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/update-password'
    | '/auth/verify-code'
    | '/'
    | '/auth'
    | '/mobility/forecast'
    | '/mobility/security'
    | '/mobility/variables'
    | '/settings/companies'
    | '/settings/users'
    | '/mobility'
    | '/settings/roles'
    | '/settings/roles/$roleId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/auth'
    | '/_dashboard/monitoring'
    | '/_dashboard/profile'
    | '/auth/forgot-password'
    | '/auth/update-password'
    | '/auth/verify-code'
    | '/_dashboard/'
    | '/auth/'
    | '/_dashboard/mobility/forecast'
    | '/_dashboard/mobility/security'
    | '/_dashboard/mobility/variables'
    | '/_dashboard/settings/companies'
    | '/_dashboard/settings/users'
    | '/_dashboard/mobility/'
    | '/_dashboard/settings/roles/'
    | '/_dashboard/settings/roles/$roleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/verify-code': {
      id: '/auth/verify-code'
      path: '/verify-code'
      fullPath: '/auth/verify-code'
      preLoaderRoute: typeof AuthVerifyCodeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/monitoring': {
      id: '/_dashboard/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof DashboardMonitoringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mobility/': {
      id: '/_dashboard/mobility/'
      path: '/mobility'
      fullPath: '/mobility'
      preLoaderRoute: typeof DashboardMobilityIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/users': {
      id: '/_dashboard/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof DashboardSettingsUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/companies': {
      id: '/_dashboard/settings/companies'
      path: '/settings/companies'
      fullPath: '/settings/companies'
      preLoaderRoute: typeof DashboardSettingsCompaniesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mobility/variables': {
      id: '/_dashboard/mobility/variables'
      path: '/mobility/variables'
      fullPath: '/mobility/variables'
      preLoaderRoute: typeof DashboardMobilityVariablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mobility/security': {
      id: '/_dashboard/mobility/security'
      path: '/mobility/security'
      fullPath: '/mobility/security'
      preLoaderRoute: typeof DashboardMobilitySecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mobility/forecast': {
      id: '/_dashboard/mobility/forecast'
      path: '/mobility/forecast'
      fullPath: '/mobility/forecast'
      preLoaderRoute: typeof DashboardMobilityForecastRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/roles/': {
      id: '/_dashboard/settings/roles/'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof DashboardSettingsRolesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/roles/$roleId/': {
      id: '/_dashboard/settings/roles/$roleId/'
      path: '/settings/roles/$roleId'
      fullPath: '/settings/roles/$roleId'
      preLoaderRoute: typeof DashboardSettingsRolesRoleIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardMonitoringRoute: typeof DashboardMonitoringRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardMobilityForecastRoute: typeof DashboardMobilityForecastRoute
  DashboardMobilitySecurityRoute: typeof DashboardMobilitySecurityRoute
  DashboardMobilityVariablesRoute: typeof DashboardMobilityVariablesRoute
  DashboardSettingsCompaniesRoute: typeof DashboardSettingsCompaniesRoute
  DashboardSettingsUsersRoute: typeof DashboardSettingsUsersRoute
  DashboardMobilityIndexRoute: typeof DashboardMobilityIndexRoute
  DashboardSettingsRolesIndexRoute: typeof DashboardSettingsRolesIndexRoute
  DashboardSettingsRolesRoleIdIndexRoute: typeof DashboardSettingsRolesRoleIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMonitoringRoute: DashboardMonitoringRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardMobilityForecastRoute: DashboardMobilityForecastRoute,
  DashboardMobilitySecurityRoute: DashboardMobilitySecurityRoute,
  DashboardMobilityVariablesRoute: DashboardMobilityVariablesRoute,
  DashboardSettingsCompaniesRoute: DashboardSettingsCompaniesRoute,
  DashboardSettingsUsersRoute: DashboardSettingsUsersRoute,
  DashboardMobilityIndexRoute: DashboardMobilityIndexRoute,
  DashboardSettingsRolesIndexRoute: DashboardSettingsRolesIndexRoute,
  DashboardSettingsRolesRoleIdIndexRoute:
    DashboardSettingsRolesRoleIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  AuthVerifyCodeRoute: typeof AuthVerifyCodeRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  AuthVerifyCodeRoute: AuthVerifyCodeRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
