/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as AuthVerifyCodeRouteImport } from './routes/auth/verify-code'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthVerifyCodeRoute = AuthVerifyCodeRouteImport.update({
  id: '/verify-code',
  path: '/verify-code',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/profile': typeof DashboardProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/verify-code': typeof AuthVerifyCodeRoute
  '/': typeof DashboardIndexRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/profile': typeof DashboardProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/verify-code': typeof AuthVerifyCodeRoute
  '/': typeof DashboardIndexRoute
  '/auth': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/verify-code': typeof AuthVerifyCodeRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/update-password'
    | '/auth/verify-code'
    | '/'
    | '/auth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/update-password'
    | '/auth/verify-code'
    | '/'
    | '/auth'
  id:
    | '__root__'
    | '/_dashboard'
    | '/auth'
    | '/_dashboard/profile'
    | '/auth/forgot-password'
    | '/auth/update-password'
    | '/auth/verify-code'
    | '/_dashboard/'
    | '/auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/verify-code': {
      id: '/auth/verify-code'
      path: '/verify-code'
      fullPath: '/auth/verify-code'
      preLoaderRoute: typeof AuthVerifyCodeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  AuthVerifyCodeRoute: typeof AuthVerifyCodeRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  AuthVerifyCodeRoute: AuthVerifyCodeRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
