/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as AuthVerifyCodeRouteImport } from './routes/auth/verify-code'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardVariablesRouteImport } from './routes/_dashboard/variables'
import { Route as DashboardUpdatePasswordRouteImport } from './routes/_dashboard/update-password'
import { Route as DashboardSecurityRouteImport } from './routes/_dashboard/security'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardMonitoringRouteImport } from './routes/_dashboard/monitoring'
import { Route as DashboardForecastRouteImport } from './routes/_dashboard/forecast'
import { Route as DashboardMovilityIndexRouteImport } from './routes/_dashboard/movility/index'
import { Route as DashboardSettingsUsersRouteImport } from './routes/_dashboard/settings/users'
import { Route as DashboardSettingsRolesRouteImport } from './routes/_dashboard/settings/roles'
import { Route as DashboardSettingsCompaniesRouteImport } from './routes/_dashboard/settings/companies'
import { Route as DashboardSettingsAgentsRouteImport } from './routes/_dashboard/settings/agents'
import { Route as DashboardMovilityCameraRouteRouteImport } from './routes/_dashboard/movility/$camera/route'
import { Route as DashboardSettingsModulesIndexRouteImport } from './routes/_dashboard/settings/modules/index'
import { Route as DashboardSettingsCamerasIndexRouteImport } from './routes/_dashboard/settings/cameras/index'
import { Route as DashboardSettingsModulesModuleIdRouteImport } from './routes/_dashboard/settings/modules/$moduleId'
import { Route as DashboardSettingsCamerasCameraRouteImport } from './routes/_dashboard/settings/cameras/$camera'
import { Route as DashboardMovilityCameraVolumeRouteImport } from './routes/_dashboard/movility/$camera/volume'
import { Route as DashboardMovilityCameraVelocityRouteImport } from './routes/_dashboard/movility/$camera/velocity'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthVerifyCodeRoute = AuthVerifyCodeRouteImport.update({
  id: '/verify-code',
  path: '/verify-code',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardVariablesRoute = DashboardVariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUpdatePasswordRoute = DashboardUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitoringRoute = DashboardMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForecastRoute = DashboardForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMovilityIndexRoute = DashboardMovilityIndexRouteImport.update({
  id: '/movility/',
  path: '/movility/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsUsersRoute = DashboardSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRolesRoute = DashboardSettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsCompaniesRoute =
  DashboardSettingsCompaniesRouteImport.update({
    id: '/settings/companies',
    path: '/settings/companies',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsAgentsRoute = DashboardSettingsAgentsRouteImport.update({
  id: '/settings/agents',
  path: '/settings/agents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMovilityCameraRouteRoute =
  DashboardMovilityCameraRouteRouteImport.update({
    id: '/movility/$camera',
    path: '/movility/$camera',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsModulesIndexRoute =
  DashboardSettingsModulesIndexRouteImport.update({
    id: '/settings/modules/',
    path: '/settings/modules/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsCamerasIndexRoute =
  DashboardSettingsCamerasIndexRouteImport.update({
    id: '/settings/cameras/',
    path: '/settings/cameras/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsModulesModuleIdRoute =
  DashboardSettingsModulesModuleIdRouteImport.update({
    id: '/settings/modules/$moduleId',
    path: '/settings/modules/$moduleId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsCamerasCameraRoute =
  DashboardSettingsCamerasCameraRouteImport.update({
    id: '/settings/cameras/$camera',
    path: '/settings/cameras/$camera',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMovilityCameraVolumeRoute =
  DashboardMovilityCameraVolumeRouteImport.update({
    id: '/volume',
    path: '/volume',
    getParentRoute: () => DashboardMovilityCameraRouteRoute,
  } as any)
const DashboardMovilityCameraVelocityRoute =
  DashboardMovilityCameraVelocityRouteImport.update({
    id: '/velocity',
    path: '/velocity',
    getParentRoute: () => DashboardMovilityCameraRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/forecast': typeof DashboardForecastRoute
  '/monitoring': typeof DashboardMonitoringRoute
  '/profile': typeof DashboardProfileRoute
  '/security': typeof DashboardSecurityRoute
  '/update-password': typeof DashboardUpdatePasswordRoute
  '/variables': typeof DashboardVariablesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/verify-code': typeof AuthVerifyCodeRoute
  '/': typeof DashboardIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/movility/$camera': typeof DashboardMovilityCameraRouteRouteWithChildren
  '/settings/agents': typeof DashboardSettingsAgentsRoute
  '/settings/companies': typeof DashboardSettingsCompaniesRoute
  '/settings/roles': typeof DashboardSettingsRolesRoute
  '/settings/users': typeof DashboardSettingsUsersRoute
  '/movility': typeof DashboardMovilityIndexRoute
  '/movility/$camera/velocity': typeof DashboardMovilityCameraVelocityRoute
  '/movility/$camera/volume': typeof DashboardMovilityCameraVolumeRoute
  '/settings/cameras/$camera': typeof DashboardSettingsCamerasCameraRoute
  '/settings/modules/$moduleId': typeof DashboardSettingsModulesModuleIdRoute
  '/settings/cameras': typeof DashboardSettingsCamerasIndexRoute
  '/settings/modules': typeof DashboardSettingsModulesIndexRoute
}
export interface FileRoutesByTo {
  '/forecast': typeof DashboardForecastRoute
  '/monitoring': typeof DashboardMonitoringRoute
  '/profile': typeof DashboardProfileRoute
  '/security': typeof DashboardSecurityRoute
  '/update-password': typeof DashboardUpdatePasswordRoute
  '/variables': typeof DashboardVariablesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/verify-code': typeof AuthVerifyCodeRoute
  '/': typeof DashboardIndexRoute
  '/auth': typeof AuthIndexRoute
  '/movility/$camera': typeof DashboardMovilityCameraRouteRouteWithChildren
  '/settings/agents': typeof DashboardSettingsAgentsRoute
  '/settings/companies': typeof DashboardSettingsCompaniesRoute
  '/settings/roles': typeof DashboardSettingsRolesRoute
  '/settings/users': typeof DashboardSettingsUsersRoute
  '/movility': typeof DashboardMovilityIndexRoute
  '/movility/$camera/velocity': typeof DashboardMovilityCameraVelocityRoute
  '/movility/$camera/volume': typeof DashboardMovilityCameraVolumeRoute
  '/settings/cameras/$camera': typeof DashboardSettingsCamerasCameraRoute
  '/settings/modules/$moduleId': typeof DashboardSettingsModulesModuleIdRoute
  '/settings/cameras': typeof DashboardSettingsCamerasIndexRoute
  '/settings/modules': typeof DashboardSettingsModulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_dashboard/forecast': typeof DashboardForecastRoute
  '/_dashboard/monitoring': typeof DashboardMonitoringRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/security': typeof DashboardSecurityRoute
  '/_dashboard/update-password': typeof DashboardUpdatePasswordRoute
  '/_dashboard/variables': typeof DashboardVariablesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/verify-code': typeof AuthVerifyCodeRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_dashboard/movility/$camera': typeof DashboardMovilityCameraRouteRouteWithChildren
  '/_dashboard/settings/agents': typeof DashboardSettingsAgentsRoute
  '/_dashboard/settings/companies': typeof DashboardSettingsCompaniesRoute
  '/_dashboard/settings/roles': typeof DashboardSettingsRolesRoute
  '/_dashboard/settings/users': typeof DashboardSettingsUsersRoute
  '/_dashboard/movility/': typeof DashboardMovilityIndexRoute
  '/_dashboard/movility/$camera/velocity': typeof DashboardMovilityCameraVelocityRoute
  '/_dashboard/movility/$camera/volume': typeof DashboardMovilityCameraVolumeRoute
  '/_dashboard/settings/cameras/$camera': typeof DashboardSettingsCamerasCameraRoute
  '/_dashboard/settings/modules/$moduleId': typeof DashboardSettingsModulesModuleIdRoute
  '/_dashboard/settings/cameras/': typeof DashboardSettingsCamerasIndexRoute
  '/_dashboard/settings/modules/': typeof DashboardSettingsModulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/forecast'
    | '/monitoring'
    | '/profile'
    | '/security'
    | '/update-password'
    | '/variables'
    | '/auth/forgot-password'
    | '/auth/update-password'
    | '/auth/verify-code'
    | '/'
    | '/auth/'
    | '/movility/$camera'
    | '/settings/agents'
    | '/settings/companies'
    | '/settings/roles'
    | '/settings/users'
    | '/movility'
    | '/movility/$camera/velocity'
    | '/movility/$camera/volume'
    | '/settings/cameras/$camera'
    | '/settings/modules/$moduleId'
    | '/settings/cameras'
    | '/settings/modules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forecast'
    | '/monitoring'
    | '/profile'
    | '/security'
    | '/update-password'
    | '/variables'
    | '/auth/forgot-password'
    | '/auth/update-password'
    | '/auth/verify-code'
    | '/'
    | '/auth'
    | '/movility/$camera'
    | '/settings/agents'
    | '/settings/companies'
    | '/settings/roles'
    | '/settings/users'
    | '/movility'
    | '/movility/$camera/velocity'
    | '/movility/$camera/volume'
    | '/settings/cameras/$camera'
    | '/settings/modules/$moduleId'
    | '/settings/cameras'
    | '/settings/modules'
  id:
    | '__root__'
    | '/_dashboard'
    | '/auth'
    | '/_dashboard/forecast'
    | '/_dashboard/monitoring'
    | '/_dashboard/profile'
    | '/_dashboard/security'
    | '/_dashboard/update-password'
    | '/_dashboard/variables'
    | '/auth/forgot-password'
    | '/auth/update-password'
    | '/auth/verify-code'
    | '/_dashboard/'
    | '/auth/'
    | '/_dashboard/movility/$camera'
    | '/_dashboard/settings/agents'
    | '/_dashboard/settings/companies'
    | '/_dashboard/settings/roles'
    | '/_dashboard/settings/users'
    | '/_dashboard/movility/'
    | '/_dashboard/movility/$camera/velocity'
    | '/_dashboard/movility/$camera/volume'
    | '/_dashboard/settings/cameras/$camera'
    | '/_dashboard/settings/modules/$moduleId'
    | '/_dashboard/settings/cameras/'
    | '/_dashboard/settings/modules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/verify-code': {
      id: '/auth/verify-code'
      path: '/verify-code'
      fullPath: '/auth/verify-code'
      preLoaderRoute: typeof AuthVerifyCodeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/variables': {
      id: '/_dashboard/variables'
      path: '/variables'
      fullPath: '/variables'
      preLoaderRoute: typeof DashboardVariablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/update-password': {
      id: '/_dashboard/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof DashboardUpdatePasswordRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/security': {
      id: '/_dashboard/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/monitoring': {
      id: '/_dashboard/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof DashboardMonitoringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/forecast': {
      id: '/_dashboard/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof DashboardForecastRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/movility/': {
      id: '/_dashboard/movility/'
      path: '/movility'
      fullPath: '/movility'
      preLoaderRoute: typeof DashboardMovilityIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/users': {
      id: '/_dashboard/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof DashboardSettingsUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/roles': {
      id: '/_dashboard/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof DashboardSettingsRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/companies': {
      id: '/_dashboard/settings/companies'
      path: '/settings/companies'
      fullPath: '/settings/companies'
      preLoaderRoute: typeof DashboardSettingsCompaniesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/agents': {
      id: '/_dashboard/settings/agents'
      path: '/settings/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof DashboardSettingsAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/movility/$camera': {
      id: '/_dashboard/movility/$camera'
      path: '/movility/$camera'
      fullPath: '/movility/$camera'
      preLoaderRoute: typeof DashboardMovilityCameraRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/modules/': {
      id: '/_dashboard/settings/modules/'
      path: '/settings/modules'
      fullPath: '/settings/modules'
      preLoaderRoute: typeof DashboardSettingsModulesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/cameras/': {
      id: '/_dashboard/settings/cameras/'
      path: '/settings/cameras'
      fullPath: '/settings/cameras'
      preLoaderRoute: typeof DashboardSettingsCamerasIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/modules/$moduleId': {
      id: '/_dashboard/settings/modules/$moduleId'
      path: '/settings/modules/$moduleId'
      fullPath: '/settings/modules/$moduleId'
      preLoaderRoute: typeof DashboardSettingsModulesModuleIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/cameras/$camera': {
      id: '/_dashboard/settings/cameras/$camera'
      path: '/settings/cameras/$camera'
      fullPath: '/settings/cameras/$camera'
      preLoaderRoute: typeof DashboardSettingsCamerasCameraRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/movility/$camera/volume': {
      id: '/_dashboard/movility/$camera/volume'
      path: '/volume'
      fullPath: '/movility/$camera/volume'
      preLoaderRoute: typeof DashboardMovilityCameraVolumeRouteImport
      parentRoute: typeof DashboardMovilityCameraRouteRoute
    }
    '/_dashboard/movility/$camera/velocity': {
      id: '/_dashboard/movility/$camera/velocity'
      path: '/velocity'
      fullPath: '/movility/$camera/velocity'
      preLoaderRoute: typeof DashboardMovilityCameraVelocityRouteImport
      parentRoute: typeof DashboardMovilityCameraRouteRoute
    }
  }
}

interface DashboardMovilityCameraRouteRouteChildren {
  DashboardMovilityCameraVelocityRoute: typeof DashboardMovilityCameraVelocityRoute
  DashboardMovilityCameraVolumeRoute: typeof DashboardMovilityCameraVolumeRoute
}

const DashboardMovilityCameraRouteRouteChildren: DashboardMovilityCameraRouteRouteChildren =
  {
    DashboardMovilityCameraVelocityRoute: DashboardMovilityCameraVelocityRoute,
    DashboardMovilityCameraVolumeRoute: DashboardMovilityCameraVolumeRoute,
  }

const DashboardMovilityCameraRouteRouteWithChildren =
  DashboardMovilityCameraRouteRoute._addFileChildren(
    DashboardMovilityCameraRouteRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardForecastRoute: typeof DashboardForecastRoute
  DashboardMonitoringRoute: typeof DashboardMonitoringRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardUpdatePasswordRoute: typeof DashboardUpdatePasswordRoute
  DashboardVariablesRoute: typeof DashboardVariablesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardMovilityCameraRouteRoute: typeof DashboardMovilityCameraRouteRouteWithChildren
  DashboardSettingsAgentsRoute: typeof DashboardSettingsAgentsRoute
  DashboardSettingsCompaniesRoute: typeof DashboardSettingsCompaniesRoute
  DashboardSettingsRolesRoute: typeof DashboardSettingsRolesRoute
  DashboardSettingsUsersRoute: typeof DashboardSettingsUsersRoute
  DashboardMovilityIndexRoute: typeof DashboardMovilityIndexRoute
  DashboardSettingsCamerasCameraRoute: typeof DashboardSettingsCamerasCameraRoute
  DashboardSettingsModulesModuleIdRoute: typeof DashboardSettingsModulesModuleIdRoute
  DashboardSettingsCamerasIndexRoute: typeof DashboardSettingsCamerasIndexRoute
  DashboardSettingsModulesIndexRoute: typeof DashboardSettingsModulesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardForecastRoute: DashboardForecastRoute,
  DashboardMonitoringRoute: DashboardMonitoringRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardUpdatePasswordRoute: DashboardUpdatePasswordRoute,
  DashboardVariablesRoute: DashboardVariablesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardMovilityCameraRouteRoute:
    DashboardMovilityCameraRouteRouteWithChildren,
  DashboardSettingsAgentsRoute: DashboardSettingsAgentsRoute,
  DashboardSettingsCompaniesRoute: DashboardSettingsCompaniesRoute,
  DashboardSettingsRolesRoute: DashboardSettingsRolesRoute,
  DashboardSettingsUsersRoute: DashboardSettingsUsersRoute,
  DashboardMovilityIndexRoute: DashboardMovilityIndexRoute,
  DashboardSettingsCamerasCameraRoute: DashboardSettingsCamerasCameraRoute,
  DashboardSettingsModulesModuleIdRoute: DashboardSettingsModulesModuleIdRoute,
  DashboardSettingsCamerasIndexRoute: DashboardSettingsCamerasIndexRoute,
  DashboardSettingsModulesIndexRoute: DashboardSettingsModulesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  AuthVerifyCodeRoute: typeof AuthVerifyCodeRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  AuthVerifyCodeRoute: AuthVerifyCodeRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
